[/TOMES]
	|E:SINGULARITY,
	|B:?,
	|R:?,
	|Th:?,
	|T:NON-PROPHET,
	|W:?,
[TOMES/]

[/BEGIN]
	|0:MIND!THE BOOK OF BIRACUL!THE BEGINNING!,
	|1:MIND!THE BOOK OF EIDOS!THE BEGINNING!,
	|2:MIND!THE BOOK OF RIKHARR!THE BEGINNING!!,
	|3:MIND!THE BOOK OF THETIAN!THE BEGINNING!,
	|4:MIND!THE BOOK OF TORMA!THE BEGINNING!,
	|5:MIND!THE BOOK OF WULFIAS!THE BEGINNING!,
[BEGIN/]

[/FONT]0[FONT/]

[/ACQ_E]
|1,|4,|100,
[ACQ_E/]

[/EVE_E]
2050,
[EVE_E/]

[/ACQ_UNI]|1,|4,|100,[ACQ_UNI/]

[/EVE]2003,2050,[EVE/]